### ISSUE TITLE
iPhone 5S 12.4.9 / 2.16.5 - Doesn't Load

### ISSUE THREAD

**Issue by ghost** [bradhowes/SoundFonts#1]
Hi

Nothing loading on iPhone 5S with 12.4.9
Not the instrument nor the effects.

GarageBand claims "SoundFonts is not installed on your iPhone.Install this missing Audio Unit Extension to continue using it in your song".

Doesn't load in latest apeMatrix either.

**Comment by bradhowes** [comment]
Thanks for the report. There is an issue with the latest release running on iOS older than 13.0. I have submitted an update to AppStore and it is waiting a review.

**Comment by ghost** [comment]
Working perfectly. Thank you vey  much.
