### ISSUE TITLE
Bounce Issue

### ISSUE THREAD

**Issue by J-Sher** [bradhowes/SoundFonts#2]
When I try to bounce an instance of SoundFonts in GarageBand it only renders what sounds like sine waves.
Even when I'm bouncing the track on it's own without any added plugins or tracks.

**Comment by bradhowes** [comment]
This is a known issue that I am working on. The core of it is that the internal rendering engine "forgets" its preset during this operation and so it is out-of-sync with the UI. There are other cases as well. I have a fix for one instance that I think might help your case as well. It is currently in TestFlight if you are interested in trying it out. Regardless, if you switch to another preset and then back again to the one you had before, rendering should be fixed.

Better AUv3 support is my area of focus right now, so hopefully additional improvements will be coming shortly.

**Comment by J-Sher** [comment]
Thank you for your speedy response.
I tried that method whilst playing with SoundFonts before and it fixed the issue within playback but not when rendering to an audio format.
I'd like to offer what help I can on TestFlight.
Besides that, I'm loving the ease of use of the UI and how smoothly it's running outside of that glitch.
Best of luck with fixing the issue!

**Comment by bradhowes** [comment]
Thanks! Here's a TestFlight link that should give you access to the 2.22.0 build. I've had good success with it on my iPad in GarageBand and AUM, but your feedback from using your workflows would be really helpful if/when you have the time.

https://testflight.apple.com/join/3POnXmKp
