### ISSUE TITLE
Release an Intel version on MAS

### ISSUE THREAD

**Issue by idnovic** [bradhowes/SoundFonts#6]
Please release an Intel version for the older mac models.

I would love to use this software on my mac but I do not own a apple silicon mac.
Is it doable to release an intel version?

**Comment by bradhowes** [comment]
Unfortunately, I do not have the time to do this. The support for macOS Catalyst comes pretty much for free, so there was no retooling involved. To migrate to native AppKit would take quite a bit of work. Another approach would be to move to SwiftUI, but that too involves a lot of rework.
